server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
#  server:
#    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
